#!/usr/bin/env python3
"""Writes Sources/BirdtownFlow/UI/Brand/VoiceprintData.swift from gen.py, the generator the
Home hero was designed with, so the app draws exactly the lines, colours and glows of the
approved design.

usage: python3 -I tools/voiceprint/export_swift.py
"""
import importlib.util
import sys
import os
import re

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, 'Sources', 'BirdtownFlow', 'UI', 'Brand', 'VoiceprintData.swift')

spec = importlib.util.spec_from_file_location('vp', os.path.join(HERE, 'gen.py'))
vp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vp)


def hx(h):
    return '0x' + h[1:].upper()


def f(v, nd=2):
    return vp.fmt(v, nd) if abs(v) >= 1e-9 else '0'


def rgba_parts(s):
    r, g, b, a = re.match(r'rgba\((\d+), (\d+), (\d+), ([\d.]+)\)', s).groups()
    return '0x%02X%02X%02X' % (int(r), int(g), int(b)), float(a)


lines = []
for x, amp, u, pres, loud in vp.build_lines():
    body = vp.spectrum(u)
    cq16 = round(u * 16) / 16
    lines.append('        .init(x: %s, amp: %s, presence: %s, floor: %s, body: %s, core: %s, hot: %s, sheen: %s, bloom: %s, bloomAlpha: %s),' % (
        f(x, 2), f(amp, 3), f(pres, 4),
        f(vp.BODY_FLOOR[0] + (vp.BODY_FLOOR[1] - vp.BODY_FLOOR[0]) * (1 - vp.coolness(u)), 3),
        hx(body),
        hx(vp.mix(body, vp.WARM_WHITE, vp.CORE[2])),
        hx(vp.mix(body, vp.WARM_WHITE, vp.HOT[2])),
        hx(vp.mix(body, vp.WARM_WHITE, 0.7)),
        hx(vp.mix(vp.spectrum(cq16), vp.WARM_WHITE, vp.BLOOM['whiten'])),
        f(0.1 + 0.9 * vp.coolness(cq16), 3),
    ))

# The broad haze behind the swell: one blurred ellipse with a horizontal gradient.
haze = vp.haze_divs()
hx0 = float(re.search(r'left: ([\d.]+)px', haze).group(1))
hy0 = float(re.search(r'top: ([\d.]+)px', haze).group(1))
hw = float(re.search(r'width: ([\d.]+)px', haze).group(1))
hh = float(re.search(r'height: ([\d.]+)px', haze).group(1))
stops = re.findall(r'(rgba\([^)]*\)) ([\d.]+)%', haze)
haze_stops = []
for col, pos in stops:
    h, a = rgba_parts(col)
    haze_stops.append('            .init(color: %s, alpha: %s, location: %s),' % (h, f(a), f(float(pos) / 100, 3)))

# Soft glows behind the loudest syllables.
d = vp.dx()
glow_x = [vp.RX0 + i * d for i, v in enumerate(vp.RHYTHM) if v >= 19]
glows = []
for div, cx in zip(vp.glow_divs().split('<div style=')[1:], glow_x):
    left = float(re.search(r'left: ([\d.]+)px', div).group(1))
    top = float(re.search(r'top: ([\d.]+)px', div).group(1))
    w = float(re.search(r'width: ([\d.]+)px', div).group(1))
    h = float(re.search(r'height: ([\d.]+)px', div).group(1))
    inner = re.search(r'closest-side, (rgba\([^)]*\))', div).group(1)
    col, a = rgba_parts(inner)
    glows.append('        .init(centerX: %s, rect: CGRect(x: %s, y: %s, width: %s, height: %s), color: %s, alpha: %s),'
                 % (f(cx), f(left), f(top), f(w), f(h), col, f(a, 3)))

swift = '''// Generated by tools/voiceprint/export_swift.py from tools/voiceprint/gen.py. Do not edit.
//
// The Home hero's voice: every hairline of the approved Voiceprint design (its position,
// height, presence and colours), the haze behind the swell and the glows behind the loudest
// syllables. Coordinates are in the design's 660 x 150 pt space.

import CoreGraphics

extension Voiceprint {
    static let centerY: CGFloat = %(yc)s
    /// Half-height of the loudest syllable.
    static let maxAmplitude: CGFloat = %(amax)s

    static let lines: [Line] = [
%(lines)s
    ]

    static let haze = Haze(
        rect: CGRect(x: %(hx)s, y: %(hy)s, width: %(hw)s, height: %(hh)s),
        blur: 24,
        opacity: %(hop)s,
        stops: [
%(stops)s
        ]
    )

    static let glows: [Glow] = [
%(glows)s
    ]

    /// The blurred copy of the loud lines that makes them glow.
    enum Bloom {
        static let heightFraction: CGFloat = %(bfrac)s
        static let width: CGFloat = %(bw)s
        static let blur: CGFloat = %(bblur)s
        static let opacity: Double = %(bop)s
        /// Glow behind the syllables.
        static let glowBlur: CGFloat = 12
    }
}
''' % dict(
    yc=f(vp.YC, 1), amax=f(vp.AMAX, 1), lines='\n'.join(lines),
    hx=f(hx0), hy=f(hy0), hw=f(hw), hh=f(hh), hop=f(vp.HAZE), stops='\n'.join(haze_stops),
    glows='\n'.join(glows), bfrac=f(vp.BLOOM['frac']), bw=f(vp.BLOOM['width']),
    bblur=f(vp.BLOOM['blur']), bop=f(vp.BLOOM['opacity']),
)
with open(OUT, 'w') as fh:
    fh.write(swift)
print('wrote', os.path.relpath(OUT, ROOT), len(lines), 'lines', len(glows), 'glows')
