#!/usr/bin/env python3
"""Builds every Birdtown Flow brand asset from two source images.

    python3 Tools/brand.py <artwork.png> <glyph.png>

artwork.png   square, full-bleed icon artwork (no rounded corners, no shadow), any size
              ≥ 1024 px. Generated with the Codex CLI; see docs/media/brand-sources/.
glyph.png     the mark alone, black on a transparent background, for template uses.

Writes:
    Resources/AppIcon.iconset/*.png   macOS icon sizes, Big Sur+ grid (824 px tile on 1024)
    Resources/AppIcon.icns
    docs/media/icon.png               512 px, for the README
    Sources/BirdtownFlow/UI/Brand/BrandAssets.swift
                                      the icon (no shadow) and the glyph as embedded PNG
                                      data, so the app never depends on a resource bundle

Needs Pillow (pip install pillow). Runs anywhere; macOS isn't required.
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
CANVAS = 1024
TILE = 824            # Apple's macOS icon grid: 824 px tile centred on a 1024 px canvas
SUPERSAMPLE = 4
CORNER = 0.225        # corner radius as a fraction of the tile (Apple: 185.4 px on 824)


def squircle_mask(size: int) -> Image.Image:
    """Anti-aliased tile mask: Apple's macOS template, a 22.5% corner radius."""
    big = size * SUPERSAMPLE
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big - 1, big - 1), radius=int(big * CORNER), fill=255)
    return mask.resize((size, size), Image.LANCZOS)


def tile(artwork: Image.Image) -> Image.Image:
    """The artwork cut to the macOS tile shape, on a transparent 1024 canvas, no shadow."""
    art = artwork.convert("RGBA").resize((TILE, TILE), Image.LANCZOS)
    mask = squircle_mask(TILE)
    shaped = Image.new("RGBA", (TILE, TILE), (0, 0, 0, 0))
    shaped.paste(art, (0, 0), ImageChops.multiply(mask, art.getchannel("A")))
    canvas = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    offset = (CANVAS - TILE) // 2
    canvas.alpha_composite(shaped, (offset, offset))
    return canvas


def with_shadow(icon: Image.Image) -> Image.Image:
    """Adds the soft drop shadow macOS icons carry in their own artwork."""
    alpha = icon.getchannel("A")
    shadow = Image.new("RGBA", icon.size, (0, 0, 0, 0))
    shade = alpha.point(lambda a: int(a * 0.28))
    shadow.putalpha(shade)
    shadow = shadow.filter(ImageFilter.GaussianBlur(14))
    out = Image.new("RGBA", icon.size, (0, 0, 0, 0))
    out.alpha_composite(shadow, (0, 10))
    out.alpha_composite(icon)
    return out


def glyph_image(glyph: Image.Image, size: int) -> Image.Image:
    """The mark trimmed to its bounds, centred in a square, black on transparent."""
    g = glyph.convert("RGBA")
    # Treat anything dark and opaque as ink; ignore near-white backgrounds the model may add.
    lum = g.convert("L")
    ink = ImageChops.multiply(g.getchannel("A"), lum.point(lambda v: 255 if v < 128 else 0))
    box = ink.getbbox() or (0, 0, g.width, g.height)
    ink = ink.crop(box)
    side = max(ink.size)
    pad = int(side * 0.06)
    square = Image.new("L", (side + 2 * pad, side + 2 * pad), 0)
    square.paste(ink, (pad + (side - ink.width) // 2, pad + (side - ink.height) // 2))
    square = square.resize((size, size), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), (0, 0, 0, 255))
    out.putalpha(square)
    return out


def png_bytes(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def swift_literal(name: str, data: bytes) -> str:
    encoded = base64.b64encode(data).decode()
    lines = [encoded[i:i + 100] for i in range(0, len(encoded), 100)]
    body = "\n".join(lines)
    return f'    static let {name} = """\n{body}\n"""\n'


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    artwork = Image.open(sys.argv[1])
    glyph = Image.open(sys.argv[2])

    icon = tile(artwork)
    icon_shadowed = with_shadow(icon)

    iconset = ROOT / "Resources" / "AppIcon.iconset"
    iconset.mkdir(parents=True, exist_ok=True)
    for old in iconset.glob("*.png"):
        old.unlink()
    for base in (16, 32, 128, 256, 512):
        for scale in (1, 2):
            px = base * scale
            name = f"icon_{base}x{base}{'@2x' if scale == 2 else ''}.png"
            icon_shadowed.resize((px, px), Image.LANCZOS).save(iconset / name, optimize=True)
    icon_shadowed.save(ROOT / "Resources" / "AppIcon.icns")

    media = ROOT / "docs" / "media"
    media.mkdir(parents=True, exist_ok=True)
    icon_shadowed.resize((512, 512), Image.LANCZOS).save(media / "icon.png", optimize=True)

    in_app = png_bytes(icon.resize((320, 320), Image.LANCZOS))
    mark = png_bytes(glyph_image(glyph, 96))
    swift = (
        "import AppKit\n\n"
        "// GENERATED by Tools/brand.py. Do not edit by hand.\n"
        "//\n"
        "// The app icon (tile only, no shadow) and the monochrome mark, as base64 PNG. Embedded\n"
        "// rather than shipped as resources so the app, snapshots and the CLI modes all load them\n"
        "// the same way, with no resource bundle to misplace. Exposed as `Data` (Sendable); views\n"
        "// use the cached images in `BrandImages`.\n"
        "enum BrandAssets {\n"
        + swift_literal("iconPNG", in_app)
        + swift_literal("glyphPNG", mark)
        + "\n"
        "    static let iconData = decode(iconPNG)\n"
        "    static let glyphData = decode(glyphPNG)\n\n"
        "    /// A fresh icon image. NSImage isn't Sendable, so each caller owns its copy.\n"
        "    static func iconImage() -> NSImage {\n"
        "        NSImage(data: iconData) ?? NSImage(size: NSSize(width: 1, height: 1))\n"
        "    }\n\n"
        "    /// A fresh template image of the mark: black on transparent, tinted by AppKit.\n"
        "    static func glyphImage() -> NSImage {\n"
        "        let image = NSImage(data: glyphData) ?? NSImage(size: NSSize(width: 1, height: 1))\n"
        "        image.isTemplate = true\n"
        "        return image\n"
        "    }\n\n"
        "    private static func decode(_ base64: String) -> Data {\n"
        "        Data(base64Encoded: base64.filter { !$0.isWhitespace }) ?? Data()\n"
        "    }\n"
        "}\n"
    )
    out = ROOT / "Sources" / "BirdtownFlow" / "UI" / "Brand" / "BrandAssets.swift"
    out.write_text(swift)
    print(f"icon {len(in_app) // 1024} KB, glyph {len(mark) // 1024} KB embedded; iconset + icns + README icon written")


if __name__ == "__main__":
    main()
